import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Provider>
        <body className={`${poppins.className}  antialiased`}>
          {children}
          <Toaster closeButton theme="light" richColors />
        </body>
      </Provider>
    </html>
  );
}
